### ISSUE TITLE
No Address fields when selecting contact entity

### ISSUE THREAD

**Issue by LycraLout** [rappen/LateboundConstantsGenerator#34]
When I select the contact or account entity, there are no address fields in the available attributes.

**Comment by rappen** [comment]
This will be solved in next release, as #33 is a symptom of the same behavior.
The reason is that since the address information is not technically stored on the Account/Contact entities, but on the Address entity and surfaced through _logical_ attributes on Account/Contact, they are not by default included in the list of attributes as it only contains physical attributes.

See animation on issue #33.

**Comment by LycraLout** [comment]
OK. Good stuff. Do you know when this release will be ready?

**Comment by rappen** [comment]
As soon as I have an evening to spare 😉
But with FIFA WWC ⚽ taking a break today, it is quite possible!

**Comment by rappen** [comment]
Fix has now been published!

**Comment by LycraLout** [comment]
Tool updated and confirmed working as expected. Great stuff. Thanks!
